name: bettersurvival
main: com.bettersurvival.bettersurvival.Plugin
version: 0.9.9
api-version: 1.19
author: MonsieurBoiBoi
commands:
  rain:
    description: To skip the rain with a vote !
  settings:
    description: Change some settings directly in game, see config.ylm for more
  night:
    description: To skip the night with a vote !
  death:
    description: To see your death location
  suicide:
    description: To kill yourself
  bettersurvival:
    description: BetterSurvival commands